### PR TITLE
Fix #726 num_processes automatically

### LINKED ISSUE #726: Flickering with certain set of plugins (probably async)
# Problems summary

deoplete is erratically flickering and changing completion menu.

## Expected

deoplete should not flicker.

## Environment Information

 * deoplete version(SHA1): 34ca883 (HEAD -> master, origin/master, origin/HEAD) Improve timer check (3 days ago) <Shougo Matsushita>

 * OS: ArchLinux

 * neovim/Vim version: NVIM v0.2.2

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim

if &compatible
  set nocompatible
endif

call plug#begin('~/.vim/plugged')

"Plug 'Shougo/vimproc.vim', {'do': 'make'}
Plug 'Shougo/deoplete.nvim'

Plug 'sebastianmarkow/deoplete-rust'
Plug 'zchee/deoplete-jedi'
Plug 'wellle/tmux-complete.vim'
Plug 'balta2ar/webcomplete.vim'

call plug#end()

filetype plugin indent on
syntax enable
set nocompatible
set laststatus=2
set number
set encoding=utf-8
set fileencodings=utf-8,cp1251,koi8-r,cp866
set showcmd

"let g:deoplete#sources#webcomplete#script = '~/.local/bin/bt words'
let g:deoplete#sources#webcomplete#script = 'sleep 5 && ls -1 /bin'
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

```
nvim -u min.vim
```
enter two symbols.

## Screen shot (if possible)

deoplete-flickering

I don't know why, but exactly this combination of plugins causes flickering. If I disable any one of them, it's gone. This is weird because if I simply open a new file, deoplete-rust and deoplete-jedi do not produce any results (empty file is neither rust or python code, right?), however, if I disable any of them, it becomes OK. It looks like some sort of race condition or maybe there is something in deoplete that relies on the order of dictionary key (that may be changing). I'm not sure...

Notice the config:
```
let g:deoplete#sources#webcomplete#script = 'sleep 5 && ls -1 /bin'
```
This is only for demo purpose. In real life, there is a command that executes for about 1-2 seconds. In this example, it continues to flicker just about those 5 seconds.

### PR DESCRIPTION
**Pull request by Shougo**
Please test @balta2ar.

### CODE REVIEW

**Comment by balta2ar** [comment]
It looks like it's working. Thanks!

**Comment by balta2ar** [comment]
If I start neovim and type "te" fast, I get this:

```
[deoplete] Traceback (most recent call last):                                                                                                                      
  File "/home/bz/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 206, in _gather_results                                                       
    if charpos < 0 or self._is_skip(ctx, source):                                                                                                                  
  File "/home/bz/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/child.py", line 421, in _is_skip                                                              
    return not (source.min_pattern_length <=                                                                                                                       
AttributeError: 'Source' object has no attribute 'min_pattern_length'                                                                                              
Errors from: buffer.  Use :messages / see above for error details.                                                                                                 
Press ENTER or type command to continue 
```

**Comment by Shougo** [comment]
Fixed.

**Comment by balta2ar** [comment]
I've been working with the latest deoplete and it is so far so good.

**Comment by Shougo** [comment]
I will merge it later.

**Pull request merged**
