### PR TITLE
[RFC] Fix async refresh on empty results

### PR DESCRIPTION
**Pull request by tweekmonster**
This fixes the issue mentioned in https://github.com/zchee/deoplete-jedi/pull/115

### CODE REVIEW

**Comment by tweekmonster** [comment]
Actually, this only fixes the cases where `context['is_async'] = True` and candidates is empty.  It's still a good PR to deal with the deoplete-jedi's actual refresh issue.

There is still an issue with `b:changedtick` changing as mentioned in deoplete-jedi PR.  Video for reference: https://share.esdf.io/7dQUIEqnZt/

**Comment by tweekmonster** [comment]
@Shougo Tracking `b:changedtick` only from `TextChangedI` seems to make this work correctly: https://share.esdf.io/nKsjNwv1Hd/

**Comment by Shougo** [comment]
> Actually, this only fixes the cases where context['is_async'] = True and candidates is empty. It's still a good PR to deal with the deoplete-jedi's actual refresh issue.

The fix is incomplete.

**Comment by tweekmonster** [comment]
> The fix is incomplete.

It was fixed by using tracking `b:changedtick` only from `TextChangedI`.  But, your other solution to simply ignore `b:changedtick` seems to work, too.

**Comment by tweekmonster** [comment]
To clarify: The only missing part from 0a013fb is addressing `is_async` when `merged_results` is empty.

**Pull request closed without merging**
