### PR TITLE
Use a timer thread to handle delayed completion

### PR DESCRIPTION
**Pull request by tweekmonster**
Originally #304 

@yrjan noticed that the `time.sleep()` was accumulating and causing long delays after typing a lot.  The other problem is that even if it was corrected to not block subsequent calls, the context would be old by the time completion happens.

Using `time.sleep()` with `500ms` delay to exaggerate the issue:

ezgif-8705343

Using `timer_start()` also has a nice side effect.  If you set the delay to `50ms` it will resolve the flickering when pressing backspace.  Maybe it can be set by default?

With `50ms` delay:

delay

No delay:

no delay

### CODE REVIEW

**Comment by Shougo** [comment]
LGTM

**Comment by Shougo** [comment]
@tweekmonster I cannot reproduce the delay backspace behavior  in your screenshot.

**Comment by tweekmonster** [comment]
Did you set `let g:deoplete#auto_complete_delay = 150` ?

**Comment by Shougo** [comment]
> With 50ms delay?

I have set it to 50ms.  Why 150?

**Comment by tweekmonster** [comment]
Ah, I'm sorry I forgot I didn't update the description.  50ms was the minimum that I tested that gave the desired results.  I found that 150ms was more consistent.

**Comment by tweekmonster** [comment]
I also think that this method has a slightly greater delay than the `timer_start()` method.  In this method, the context is still created and `rpcnotify()` is called.  With `timer_start()`, it could prevent the context creation/parsing and `rpcnotify()`.

**Comment by Shougo** [comment]
Hm.  VimL version is better.  I think.
This is slow.
I will revert it.

**Pull request merged**
