### PR TITLE
[WIP] Add filenames source

### PR DESCRIPTION
**Pull request by fmoralesc**
I'm not sure the behavior of this source is ideal yet, please give me suggestions. 

It probably needs to take into account the context, so completing from

~~~
rplugin/python3/deopl|
                     ^
~~~
gives
~~~
rplugin/python3/deoplete|
                        ^
~~~
What is the proper way to do this?

### CODE REVIEW

**Comment by Shougo** [comment]
Yes, you should parse input text.
Unfortunlatelly, I don't implement complete position feature.
You should wait until it.

**Comment by fmoralesc** [comment]
OK, I'll wait.

**Comment by Shougo** [comment]
I have implemented source complete position feature.
Please implement the source using it.

**Comment by fmoralesc** [comment]
I updated the source to use the complete position feature (great work on that, it's really nice to use :+1:).

**Comment by fmoralesc** [comment]
I was thinking: should this return the paths macthing the prefix, as it does now, or should it return all files in the dirname, so a fuzzy matcher could get better candidates?

**Comment by Shougo** [comment]
I think current behavior is better.

**Comment by Shougo** [comment]
Merged.  Thanks.

If you want to update it, please create another pull request.

**Comment by Shougo** [comment]
I think file name is better.
I will rename files to file.

**Comment by xHN35RQ** [comment]
:+1:

**Pull request merged**
