### PR TITLE
wait to kill python processes.

### PR DESCRIPTION
**Pull request by RyoSusami**
Add wait to kill python processes.

### CODE REVIEW

**Comment by Shougo** [comment]
Thanks.

**Comment by blueyed** [comment]
Doesn't this only wait for the first child to exit?

**Comment by blueyed** [comment]
And why is this necessary after all?

**Comment by Shougo** [comment]
> Doesn't this only wait for the first child to exit?

I will fix it later.

> And why is this necessary after all?

Because neovim exits without waiting subprocess.
Note: Vim8 does not have the problem.

**Comment by blueyed** [comment]
I think https://github.com/Shougo/deoplete.nvim/pull/631 might take care of that (childs exit when stdin gets closed).

**Comment by Shougo** [comment]
OK.  But it is big change.
I must test it before merge.

**Comment by Shougo** [comment]
More testers are needed.

**Pull request merged**
