### PR TITLE
Parse ctags tagfield to get symbol kind

### PR DESCRIPTION
**Pull request by tweekmonster**
ref #607 #648

ping @kristijanhusak

### CODE REVIEW

**Comment by Shougo** [comment]
Please test @kristijanhusak.
I think it is better solution.

**Comment by kristijanhusak** [comment]
@Shougo I agree.

@tweekmonster thanks, this is much better solution.

**Comment by Shougo** [comment]
I will merge it later.

**Comment by Shougo** [comment]
Merged.

**Pull request merged**
