### PR TITLE
sources/file: new method to get completion position

### PR DESCRIPTION
**Pull request by fmoralesc**
Use the longest path that can be constructed from context['input']

This doesn't need to parse '&isfname', is simpler, and allows completion
of filenames containing spaces.

Fixes issues described here :
https://github.com/Shougo/deoplete.nvim/commit/a65c1703c4fabf1dc159f30ca64e259f6fa6b489#commitcomment-11823924

### CODE REVIEW

**Comment by Shougo** [comment]
OK.  It seems better.
But can you change the complete position like neocomplete file source?
Please test neocomplete.
Current file source complete position behavior is different.

**Comment by kopischke** [comment]
Looks like the much saner path to tread to me – `isf` is something you only want to touch with a long, fireproof stick (preferably one remote manipulated while you hide in a fallout shelter) :).

**Comment by fmoralesc** [comment]
I updated this with some fixes. I'm not sure what in neocomplete's behavior is different, and why it is preferable, I'd be glad if @Shougo could point that out to me.

**Comment by Shougo** [comment]
Merged.

OK, I explain it.

If `/foo/bar/|` : (`|` is cursor position)

neocomplete completes `/foo/bar/baz` from last slash.
current deoplete file source completes `/foo/bar/baz` from first slash.

I think neocomplete behavior is better.
Because, neocomplete file source also can complete from other source(For example: buffer).
And complete string is not long.

**Comment by Shougo** [comment]
Another improvement:

The file source should convert `\` to `/`.
This routine seems not supported Windows path separator (backslash).

**Pull request merged**
