### PR TITLE
Use GitHub action

### PR DESCRIPTION
**Pull request by MindTooth**
Hi,

Noticed the other day that the CI had failed and I noticed that the repo was still using Travis.  Figured I would give it a go at using GitHub Action.

* Some env variables are set manually to override the Makefile
* Tries to use as many actions instead of manual tasks

This now has 16 jobs with a various combination of Neovim/Vim & Python.  I imagine that not every one is necessary.

Thoughts?

---

View an [example job](https://github.com/MindTooth/deoplete.nvim/actions/runs/484989468) here.

### CODE REVIEW

**Comment by Shougo** [comment]
Thanks.  It seems good.
Can you create the PR for denite.nvim?

**Comment by Shougo** [comment]
> This now has 16 jobs with a various combination of Neovim/Vim & Python. I imagine that not every one is necessary.

Hm.  I think Python 3.6 tests can be skipped.
And all combinations are not needed.

**Comment by MindTooth** [comment]
> Can you create the PR for denite.nvim?

Sure can when we are happy with this one. 👍🏻 

I have removed Python 3.6 & Vim.  Also fixed `version:` that was broken.

Do you want me to add some comments/docs, or is it self-explanatory enough?

**Comment by Shougo** [comment]
> Do you want me to add some comments/docs, or is it self-explanatory enough?

LGTM

**Comment by Shougo** [comment]
Merged.  Thanks.

**Comment by Shougo** [comment]
I will port it to dein.vim later.

**Comment by Shougo** [comment]
I have ported and I have removed Travis integration finally.

**Comment by MindTooth** [comment]
> I have ported and I have removed Travis integration finally.

Nice!  Glad I could help.

**Pull request merged**
