### PR TITLE
[RFC] Fix #471 Parallel

### LINKED ISSUE #471: Dynamic completion candidates update?
Different sources have different speeds. Some are very fast - like "buffer" and "around", some may take many seconds to gather candidates from, e.g. "tag" source. Can we show the completion candidates as they become avaliable from the source? I.e. when I start typing, I should instantly get completions from "buffer" and "around", and if I'm willing to wait for so many seconds - the candidates from "tag" would appear and the candidates list will be dynamically redrawn.

### PR DESCRIPTION
**Pull request by Shougo**
~~It is on WIP.~~

~~Note: profile and debug feature is not supported.~~

You can test the feature!

### CODE REVIEW

**Comment by Shougo** [comment]
The current status is:

The refactoring before threading is done.
The next is threading support.

**Comment by Shougo** [comment]
> Note: profile and debug feature is not supported.

I will fix the problem later.

**Comment by Shougo** [comment]
@roxma I have added the threading feature.
But it does not work...
Can you test the plugin?

**Comment by Shougo** [comment]
attach vim in another thread seems does not work.
It works on nvim-completion-manager though.

**Comment by Shougo** [comment]
I have updated it.
It still WIP though.

**Comment by Shougo** [comment]
I have implemented the feature.
But it will be crashed by `Out of memory`.
Why?

**Comment by Shougo** [comment]
The more testers and the code reviewers are needed.

**Comment by Mte90** [comment]
I can help to test on vim in case :-) What is the way to get that branch with vundle?

**Comment by deathmaz** [comment]
any configuration needed to make it to work? i'm on linux and it didn't work when i switched the branch

**Comment by Shougo** [comment]
> I can help to test on vim in case :-) What is the way to get that branch with vundle?

Vundle does not support branch swich.
You can switch the branch manually.

> any configuration needed to make it to work? i'm on linux and it didn't work when i switched the branch

No additional configuration is needed.
Note:  It is very experimental.  It is slow.  You must wait few second.

**Comment by deathmaz** [comment]
@Shougo yes, it works after i wait for a few seconds, do you need to test some specific things?

**Comment by Shougo** [comment]
> @Shougo yes, it works after i wait for a few seconds, do you need to test some specific things?

Nothing.  It works.  But it is very experimental.

I'm waiting for https://github.com/neovim/python-client/pull/294.

**Comment by Shougo** [comment]
I will change the implementation using msgpack instead of Vim variables.

**Comment by Shougo** [comment]
I have completed the development.

@blueyed Profile and debug feature tests are needed.

**Comment by Shougo** [comment]
It uses msgpack instead.

**Comment by wsdjeg** [comment]
@Shougo I just get some error with this branch, and easy to test:

here is my content in current buffer

```md
欢迎来到 <img src="https://spacevim.org/SpaceVim.png" height="17" width="17"> **SpaceVim** 维基, 一个关于 SpaceVim 的资源导航!

- [Introduction](Introduction)  
- **[FAQ](FAQ)**
- [Progress/Roadmap](Progress)
- [Features](Features)
- [Project layout](project_layout)

## Users

- [Documentation](https://spacevim.org/documentation)
    - [Quick start guide](quick-start-guide)
- [Getting Help](getting-help)
- [Install](Installing-SpaceVim)
- [Update](Update)
- [Community](http://spacevim.org/community/)

## Developers

the wiki is generated from [`wiki/`](https://github.com/SpaceVim/SpaceVim/tree/master/wiki) directory automatically, if you want to contribute to the wiki, please use pull request.

- [Support SpaceVim](support-spacevim)
    - [contribute to SpaceVim](https://github.com/SpaceVim/SpaceVim/blob/master/CONTRIBUTING.md)
    - [Write post about SpaceVim](write-post-about-spacevim)
- [Credits & Thanks](credits--thanks)
```

test step:

1. :call  cursor(1,124)
2.  press `a<space>`

I get:

```
"wiki/cn/Home.markdown" 25L, 953C written
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 60, in completion_begin
[deoplete]     is_async, position, candidates = self.merge_results(context)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 107, in merge_results
[deoplete]     result = parent.merge_results(context)
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 46, in merge_results
[deoplete]     queue_id = self._put('merge_results', [context])
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 85, in _put
[deoplete]     self._proc.write({'name': name, 'args': args, 'queue_id': queue_id})
[deoplete]   File "/home/wsdjeg/.cache/vimfiles/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/process.py", line 68, in write
[deoplete]     self._proc.stdin.write(msgpack.packb(expr, use_bin_type=True))
[deoplete]   File "/home/wsdjeg/.local/lib/python3.6/site-packages/msgpack/__init__.py", line 47, in packb
[deoplete]     return Packer(**kwargs).pack(o)
[deoplete]   File "msgpack/_packer.pyx", line 231, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3661)
[deoplete]   File "msgpack/_packer.pyx", line 233, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:3503)
[deoplete]   File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
[deoplete]   File "msgpack/_packer.pyx", line 221, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:3230)
[deoplete]   File "msgpack/_packer.pyx", line 192, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2657)
[deoplete]   File "msgpack/_packer.pyx", line 174, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:2395)
[deoplete] UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-1: surrogates not allowed
[deoplete] Error while gathering completions.  Use :messages for error details.
```

**Comment by bfredl** [comment]
You need to setup msgpack to use to use surrogateescape (just like the client), i e `Packer(unicode_errors="surrogateescape")`

**Comment by Shougo** [comment]
@wsdjeg I have fixed the error.  Please update.

**Comment by wsdjeg** [comment]
@Shougo Thanks, It works well for me now.

**Comment by Shougo** [comment]
Thanks.

**Comment by Shougo** [comment]
I will improve the performance more.

Please wait.

**Comment by Shougo** [comment]
Profile and debugging log feature does not work.
I will fix it later.

**Comment by balta2ar** [comment]
Once it's ready, could you please record a demo showing the difference that it made? The strong side, so to speak.
Also, will it change how deople pluings should be written? Is it backwards compatible?

**Comment by Shougo** [comment]
I have updated the performance.
Please update.

**Comment by Shougo** [comment]
> Also, will it change how deople pluings should be written? Is it backwards compatible?

Of course it is backward compatible.  No need to fix the sources.

> Once it's ready, could you please record a demo showing the difference that it made? The strong side, so to speak.

I have not the demo.

**Comment by Shougo** [comment]
Here is the log of master branch profile.

```
2018-01-29 11:00:42,779 DEBUG    (deoplete.core) Profile Start: around
2018-01-29 11:00:42,781 DEBUG    (deoplete.core) Profile End  : around                    time=0.0011250000
2018-01-29 11:00:42,783 DEBUG    (deoplete.core) Profile Start: dictionary
2018-01-29 11:00:42,783 DEBUG    (deoplete.core) Profile End  : dictionary                time=0.0000420000
2018-01-29 11:00:42,784 DEBUG    (deoplete.core) Profile Start: buffer
2018-01-29 11:00:42,784 DEBUG    (deoplete.core) Profile End  : buffer                    time=0.0003810000
2018-01-29 11:00:42,785 DEBUG    (deoplete.core) Profile Start: tag
2018-01-29 11:00:42,786 DEBUG    (deoplete.core) Profile End  : tag                       time=0.0007940000
2018-01-29 11:00:42,787 DEBUG    (deoplete.core) Profile Start: matcher_fuzzy
2018-01-29 11:00:42,788 DEBUG    (deoplete.core) Profile End  : matcher_fuzzy             time=0.0007520000
2018-01-29 11:00:42,788 DEBUG    (deoplete.core) Profile Start: sorter_rank
2018-01-29 11:00:42,788 DEBUG    (deoplete.core) Profile End  : sorter_rank               time=0.0000280000
2018-01-29 11:00:42,788 DEBUG    (deoplete.core) Profile Start: converter_remove_overlap
2018-01-29 11:00:42,788 DEBUG    (deoplete.core) Profile End  : converter_remove_overlap  time=0.0000080000
2018-01-29 11:00:42,788 DEBUG    (deoplete.core) Profile Start: converter_truncate_abbr
2018-01-29 11:00:42,788 DEBUG    (deoplete.core) Profile End  : converter_truncate_abbr   time=0.0000160000
2018-01-29 11:00:42,789 DEBUG    (deoplete.core) Profile Start: converter_truncate_kind
2018-01-29 11:00:42,789 DEBUG    (deoplete.core) Profile End  : converter_truncate_kind   time=0.0000080000
2018-01-29 11:00:42,789 DEBUG    (deoplete.core) Profile Start: converter_truncate_menu
2018-01-29 11:00:42,789 DEBUG    (deoplete.core) Profile End  : converter_truncate_menu   time=0.0000150000
2018-01-29 11:00:42,789 DEBUG    (deoplete.core) Profile Start: matcher_fuzzy
2018-01-29 11:00:42,790 DEBUG    (deoplete.core) Profile End  : matcher_fuzzy             time=0.0000060000
2018-01-29 11:00:42,790 DEBUG    (deoplete.core) Profile Start: sorter_rank
2018-01-29 11:00:42,790 DEBUG    (deoplete.core) Profile End  : sorter_rank               time=0.0000150000
2018-01-29 11:00:42,790 DEBUG    (deoplete.core) Profile Start: converter_remove_overlap
2018-01-29 11:00:42,790 DEBUG    (deoplete.core) Profile End  : converter_remove_overlap  time=0.0000070000
2018-01-29 11:00:42,790 DEBUG    (deoplete.core) Profile Start: converter_truncate_abbr
2018-01-29 11:00:42,790 DEBUG    (deoplete.core) Profile End  : converter_truncate_abbr   time=0.0000070000
2018-01-29 11:00:42,790 DEBUG    (deoplete.core) Profile Start: converter_truncate_kind
2018-01-29 11:00:42,790 DEBUG    (deoplete.core) Profile End  : converter_truncate_kind   time=0.0000050000
2018-01-29 11:00:42,790 DEBUG    (deoplete.core) Profile Start: converter_truncate_menu
2018-01-29 11:00:42,791 DEBUG    (deoplete.core) Profile End  : converter_truncate_menu   time=0.0000060000
2018-01-29 11:00:42,791 DEBUG    (deoplete.core) Profile Start: matcher_fuzzy
2018-01-29 11:00:42,791 DEBUG    (deoplete.core) Profile End  : matcher_fuzzy             time=0.0000130000
2018-01-29 11:00:42,791 DEBUG    (deoplete.core) Profile Start: sorter_rank
2018-01-29 11:00:42,791 DEBUG    (deoplete.core) Profile End  : sorter_rank               time=0.0000150000
2018-01-29 11:00:42,791 DEBUG    (deoplete.core) Profile Start: converter_remove_overlap
2018-01-29 11:00:42,792 DEBUG    (deoplete.core) Profile End  : converter_remove_overlap  time=0.0000060000
2018-01-29 11:00:42,792 DEBUG    (deoplete.core) Profile Start: converter_truncate_abbr
2018-01-29 11:00:42,792 DEBUG    (deoplete.core) Profile End  : converter_truncate_abbr   time=0.0000070000
2018-01-29 11:00:42,792 DEBUG    (deoplete.core) Profile Start: converter_truncate_kind
2018-01-29 11:00:42,792 DEBUG    (deoplete.core) Profile End  : converter_truncate_kind   time=0.0000050000
2018-01-29 11:00:42,792 DEBUG    (deoplete.core) Profile Start: converter_truncate_menu
2018-01-29 11:00:42,792 DEBUG    (deoplete.core) Profile End  : converter_truncate_menu   time=0.0000060000
2018-01-29 11:00:42,793 DEBUG    (deoplete.core) Profile Start: matcher_fuzzy
2018-01-29 11:00:42,793 DEBUG    (deoplete.core) Profile End  : matcher_fuzzy             time=0.0000730000
2018-01-29 11:00:42,793 DEBUG    (deoplete.core) Profile Start: sorter_rank
2018-01-29 11:00:42,793 DEBUG    (deoplete.core) Profile End  : sorter_rank               time=0.0000140000
2018-01-29 11:00:42,793 DEBUG    (deoplete.core) Profile Start: converter_remove_overlap
2018-01-29 11:00:42,793 DEBUG    (deoplete.core) Profile End  : converter_remove_overlap  time=0.0000060000
2018-01-29 11:00:42,793 DEBUG    (deoplete.core) Profile Start: converter_truncate_abbr
2018-01-29 11:00:42,793 DEBUG    (deoplete.core) Profile End  : converter_truncate_abbr   time=0.0000060000
2018-01-29 11:00:42,794 DEBUG    (deoplete.core) Profile Start: converter_truncate_kind
2018-01-29 11:00:42,794 DEBUG    (deoplete.core) Profile End  : converter_truncate_kind   time=0.0000050000
2018-01-29 11:00:42,794 DEBUG    (deoplete.core) Profile Start: converter_truncate_menu
2018-01-29 11:00:42,794 DEBUG    (deoplete.core) Profile End  : converter_truncate_menu   time=0.0000050000
2018-01-29 11:00:42,976 DEBUG    (deoplete.core) Profile Start: matcher_fuzzy
2018-01-29 11:00:42,977 DEBUG    (deoplete.core) Profile End  : matcher_fuzzy             time=0.0001620000
2018-01-29 11:00:42,977 DEBUG    (deoplete.core) Profile Start: sorter_rank
```

**Comment by Shougo** [comment]
Here is the parallel branch log.


```
2018-01-29 14:19:05,794 DEBUG    (deoplete.core) completion_begin: date date hogera hoge
2018-01-29 14:19:05,800 DEBUG    (deoplete.child) main_loop: begin
2018-01-29 14:19:05,800 DEBUG    (deoplete.child) main_loop: merge_results
2018-01-29 14:19:05,815 DEBUG    (deoplete.child) main_loop: begin
2018-01-29 14:19:05,815 DEBUG    (deoplete.child) main_loop: merge_results
2018-01-29 14:19:05,830 DEBUG    (deoplete.child) main_loop: begin
2018-01-29 14:19:05,830 DEBUG    (deoplete.child) main_loop: merge_results
2018-01-29 14:19:05,846 DEBUG    (deoplete.child) main_loop: begin
2018-01-29 14:19:05,846 DEBUG    (deoplete.child) main_loop: merge_results
2018-01-29 14:19:05,847 DEBUG    (deoplete.child) Profile Start: matcher_fuzzy
2018-01-29 14:19:05,847 DEBUG    (deoplete.child) Profile End  : matcher_fuzzy             time=0.0003270000
2018-01-29 14:19:05,848 DEBUG    (deoplete.child) Profile Start: sorter_rank
2018-01-29 14:19:05,848 DEBUG    (deoplete.child) Profile End  : sorter_rank               time=0.0000220000
2018-01-29 14:19:05,848 DEBUG    (deoplete.child) Profile Start: converter_remove_overlap
2018-01-29 14:19:05,848 DEBUG    (deoplete.child) Profile End  : converter_remove_overlap  time=0.0000060000
2018-01-29 14:19:05,848 DEBUG    (deoplete.child) Profile Start: converter_truncate_abbr
2018-01-29 14:19:05,848 DEBUG    (deoplete.child) Profile End  : converter_truncate_abbr   time=0.0000120000
2018-01-29 14:19:05,848 DEBUG    (deoplete.child) Profile Start: converter_truncate_kind
2018-01-29 14:19:05,848 DEBUG    (deoplete.child) Profile End  : converter_truncate_kind   time=0.0000060000
2018-01-29 14:19:05,848 DEBUG    (deoplete.child) Profile Start: converter_truncate_menu
2018-01-29 14:19:05,848 DEBUG    (deoplete.child) Profile End  : converter_truncate_menu   time=0.0000110000
2018-01-29 14:19:05,857 DEBUG    (deoplete.core) completion_end: date date hogera hoge
2018-01-29 14:19:06,855 DEBUG    (deoplete.core) completion_begin: date date hogera hogeraj
```

**Comment by Shougo** [comment]
You see the difference between the logs.

master: Almost 200ms
parallel: Almost 60ms

**Comment by jsfaint** [comment]
Did anyone use parallel branch on windows?
I switched to parallel branch and got this message on neovim startup
image

**Comment by Shougo** [comment]
I will add the error check later.
I think python exe(`get(g:, 'python3_host_prog', 'python3')`) is not in `$PATH`.

**Comment by jsfaint** [comment]
@Shougo Sorry, I checked the vimrc, the `g:python3_host_prog` is only set for vim
```
if !has('nvim')
  let g:python3_host_prog = 'C:/Users/jia.sui/AppData/Local/Programs/Python/Python36/python.exe'
endif
```

After set the `g:python3_host_prog` and then try to use the completion.
There are 4 python processes eat up my CPU, and there is no completion window showed up
image

**Comment by Shougo** [comment]
I don't know why it does not work.
You can research the problem.

**Comment by balta2ar** [comment]
You're using msgpack here. What's the reasoning for this choice? Could it be JSON or Pickle instead? I'm not questioning the choice, it's just good for my own knowledge to know which one to pick in which situation.

**Comment by Shougo** [comment]
> You're using msgpack here. What's the reasoning for this choice? Could it be JSON or Pickle instead? I'm not questioning the choice, it's just good for my own knowledge to know which one to pick in which situation.

It is good question.
I have choosed the library because:

* neovim uses it(No additional dependency).
* It supports stream decode.  It is useful for standard input/output communication.
* The decode/encode performance is good than json.

**Comment by Shougo** [comment]
Merged.

**Comment by balta2ar** [comment]
Unfortunately, it broke my deoplete plugin...

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/user/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 63, in completion_begin
[deoplete]     is_async, position, candidates = self.merge_results(context)
[deoplete]   File "/home/user/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 110, in merge_results
[deoplete]     result = parent.merge_results(context)
[deoplete]   File "/home/user/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 51, in merge_results
[deoplete]     get = self._get(queue_id)
[deoplete]   File "/home/user/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 91, in _get
[deoplete]     return [x for x in self._proc.communicate(15)
[deoplete]   File "/home/user/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/parent.py", line 92, in <listcomp>
[deoplete]     if x['queue_id'] == queue_id]
[deoplete] TypeError: 'int' object is not subscriptable
[deoplete] Error while gathering completions.  Use :messages for error details.
```

**Comment by Shougo** [comment]
@balta2ar I cannot reproduce the problem.
Please create the new issue.  We have not ESP skills.

> Unfortunately, it broke my deoplete plugin...

What is the plugin?

**Comment by balta2ar** [comment]
It looks like I found the problem in my code: I had several `print`s here and there in my plugin, so their output of course was unexpected to the `Parent` class. I removed `print`s, and the errors were gone. I know it's not the issue of the plugin, but is there anything that can be done to help find such problems easier? How about printing a friendly message saying "Unexpected output from child process. Are you printing something to stdout there?". That's just an idea though.

But there is still a problem. My plugin relies on the `is_async` flag logic: I expect that deoplete will keep calling my `gather_candidates` method until I set `context["is_async"]` to False. When I process data in the background, I keep setting `is_async` to True. But it appears that deoplete does not call me again when my results are ready. Could you please check this behavior?

**Comment by Shougo** [comment]
> How about printing a friendly message saying "Unexpected output from child process. Are you printing something to stdout there?". That's just an idea though.

If you can implement the feature, should be.
The PR is wellcome.

>  But it appears that deoplete does not call me again when my results are ready. Could you please check this behavior?

Hm.  I will check the behavior later.
Please create the new issue for it.

**Comment by bfredl** [comment]
To support using `print()` in children could use stdout redirection (in the child) like the script host: https://github.com/neovim/python-client/blob/320cb7d92c2bfaabe10bd278efd99361ebabc2bf/neovim/plugin/script_host.py#L64

**Comment by bfredl** [comment]
Or maybe just `sys.stdout = sys.stderr`, and then handle stderr in the parent...

**Comment by Shougo** [comment]
OK.  I will test that.

**Comment by Shougo** [comment]
```diff
diff --git a/rplugin/python3/deoplete/dp_main.py b/rplugin/python3/deoplete/dp_main.py
index 04e0448..dff1e84 100644
--- a/rplugin/python3/deoplete/dp_main.py
+++ b/rplugin/python3/deoplete/dp_main.py
@@ -5,6 +5,7 @@
 # ============================================================================
 
 import sys
+import io
 
 from neovim import attach
 
@@ -28,10 +29,21 @@ def attach_vim(serveraddr):
     return vim
 
 
+class RedirectStream(io.IOBase):
+    def __init__(self, redirect_handler):
+        self.redirect_handler = redirect_handler
+
+    def write(self, data):
+        self.redirect_handler(data)
+
+    def writelines(self, seq):
+        self.redirect_handler('\n'.join(seq))
+
 def main(serveraddr):
     vim = attach_vim(serveraddr)
     from deoplete.child import Child
     from deoplete.util import error_tb
+    sys.stdout = RedirectStream(lambda data: vim.out_write(data))
     try:
         child = Child(vim)
         child.main()
diff --git a/rplugin/python3/deoplete/process.py b/rplugin/python3/deoplete/process.py
index d1ac7b3..e81ca35 100644
--- a/rplugin/python3/deoplete/process.py
+++ b/rplugin/python3/deoplete/process.py
@@ -52,7 +52,11 @@ class Process(object):
 
     def enqueue_output(self):
         while self._proc:
-            b = self._proc.stdout.read(1)
+            # b = self._proc.stdout.raw.read(102400)
+            b = self._proc.stderr.raw.read(102400)
+            if b == b'':
+                return
+
             self._unpacker.feed(b)
             for child_out in self._unpacker:
                 self._queue_out.put(child_out)
```

Hm.   It may be better.

**Comment by Shougo** [comment]
@balta2ar I have fixed stdout problem completely.

**Comment by bfredl** [comment]
Why are you sending the msgpack over stderr? That will indeed cause all sorts of trouble... Instead, use the original stdout stream:

    self.stdout = sys.stdout # use it for msgpack
    sys.stdout = RedirectStream(...) # gets print() out of the way

**Comment by Shougo** [comment]
Yes.  I have fixed it in the latest version.

**Pull request merged**
