### PR TITLE
Do not call 'deoplete#mappings#_set_completeopt' in manual mode

### PR DESCRIPTION
**Pull request by blueyed**
Changing `'completeopt'` seems to be necessary only for the
auto-completion mode?!

### CODE REVIEW

**Comment by Shougo** [comment]
I don't think so.  Closing.

**Comment by blueyed** [comment]
I don't get it, please explain.

The manual completion is invoked through a user's script, which then can ensure the proper setup for `'completeopt'`.

With this patch/PR it's easier to call the manual completion, without having to (re)store the `'completeopt'` setting.

As far as I understood it, the changing of `'completeopt'` is necessary to work in the context of automatic completion, to not interfere with the user's typing process.  But in the case of manually triggering it this should not be required?!

**Comment by Shougo** [comment]
I can implement it more properly.
But I don't want to add the restore feature.
Because, it may conflict the user config or user settings.

Example: https://github.com/Shougo/deoplete.nvim/issues/206

It seems the restore feature is broken.

**Comment by Shougo** [comment]
If the feature is really needed, other needed people is needed.

**Comment by blueyed** [comment]
Is #206 really related?  According to https://github.com/Shougo/deoplete.nvim/issues/206#issuecomment-196324186 it's not?!

This PR / suggestion does not have a (new) restore feature, but keeps using the existing one.
Do you mean to remove that one (again)?

**Comment by Shougo** [comment]
I have implemented it.

**Comment by blueyed** [comment]
Thanks!

**Pull request closed without merging**
