### PR TITLE
Skip creating tag abbreviation for definitions that contain js require().

### PR DESCRIPTION
**Pull request by kristijanhusak**
Fixes issue mentioned in comment https://github.com/Shougo/deoplete.nvim/pull/607#issuecomment-364050997

### CODE REVIEW

**Comment by tweekmonster** [comment]
@kristijanhusak I don't like the way a blacklist is being used here.  `require()` isn't exclusive to javascript.  I think the ctag attributes will need to be parsed to determine if it's actually a function: http://docs.ctags.io/en/latest/format.html

**Comment by kristijanhusak** [comment]
@tweekmonster what other language uses `require()`?

I don't think we can get an attribute that will tell us that it's javascript definition, correct me if i'm wrong.

One thing we can do is determine the extension of the file in the tag definition, and act according to that.

**Comment by tweekmonster** [comment]
> @tweekmonster what other language uses require()?

PHP.  I could also create a `require()` function in C or most any other language for that matter.  It also looks like the blacklist would match `not_require()` as well.

> I don't think we can get an attribute that will tell us that it's javascript definition, correct me if i'm wrong.

You can get the filetype from the `context` variable.  But, I was referring to ctag's attributes.

From your example:

```
CustomerValidator	lib/domain/user/signup_validator.js	/^const CustomerValidator = require('..\/..\/customer\/customer_validator');$/;"	C
```

The `C` at the end is denoting that the tag is a constant.  For functions, it would be `f`.  But, there's more to the ctag format that might not make this a straight-forward evaluation of the last character.

The other thing is that only the first 3 fields (before the `;"`) is actually required.  I wasn't sure if universal-ctags always added the extra fields, so I just stuck with regex matching, which I'll admit was pretty naive.

**Comment by kristijanhusak** [comment]
@tweekmonster You are right, i didn't think about someone creating that function themselves.
I know for those attributes, but i don't think they are reliable enough.

What are your suggestions?

**Comment by tweekmonster** [comment]
Created a PR that should address your issue and incidentally adds a little more useful info to other tag symbols.  If people have tags that are generated without the extra tagfields, then no special treatment.

**Comment by kristijanhusak** [comment]
Closing in favor of https://github.com/Shougo/deoplete.nvim/pull/650

**Pull request closed without merging**
