### PR TITLE
Commented out 2 rogue debug statements

### PR DESCRIPTION
**Pull request by nhooyr**
title

### CODE REVIEW

**Comment by yevhen-m** [comment]
Thanks for your help!

**Comment by yevhen-m** [comment]
Could you please tell me, how to fix such bugs? Do you know deoplete code base well, or you just know, how to debug such things?

**Comment by nhooyr** [comment]
@yevhen-m Shougo has made the same mistake before, he sometimes forgets the debug statements. I just figured it was probably that, and did a simple regex search for debug statements and found these two to be not commented. I was going to run neovim in verbose mode (`:h verbose`) to figure it out if that didn't work.

**Comment by yevhen-m** [comment]
Thanks.

**Comment by Shougo** [comment]
Thank you!

**Pull request merged**
