### PR TITLE
Base: move most of attribute initialization out of __init__

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by Shougo** [comment]
Merged.

**Comment by lambdalisue** [comment]
I don't get why this change is required. All instance including sub-class would share the insatnce of `matchers`, `sorters`, `converters`, `filetypes`, and `disabled_syntaxes` so I think it's a kind trap.

For example, are you sure that the following behavior is what you expect?

```python
class A:
    foo = []

class B(A):
    def __init__(self):
        self.foo.append('Hello')

class C(A):
    def __init__(self):
        self.foo.append('Goodbye')

print(C().foo)
print(B().foo)
print(A().foo)

# ['Goodbye']
# ['Goodbye', 'Hello']
# ['Goodbye', 'Hello']
```

**Comment by Shougo** [comment]
I have reverted it.

Reason: @lambdalisue 's comment.

**Comment by blueyed** [comment]
Yes, sorry - it does not work for mutable types.
Thanks for reverting already.

**Pull request merged**
