### PR TITLE
Vim8 support using nvim-yarp and vim-hug-neovim-rpc

### LINKED ISSUE #339: Any plan to porting Deoplete to Vim 8?
I have started using Deoplete and so far I love it. If only it worked in Vim… Do you have any plan to port Deoplete (or Neocomplete) to Vim 8, leveraging the new asynchronous features of Vim?

### PR DESCRIPTION
**Pull request by Shougo**
~~I have added the test code for nvim-yarp.~~
~~But it is freezed.  Why?~~

@roxma

More Vim8 testers are needed.
Especially, Windows users.

Fix #339

Requirements:

https://github.com/roxma/nvim-yarp

https://github.com/roxma/vim-hug-neovim-rpc For Vim8

### CODE REVIEW

**Comment by roxma** [comment]
Is there a minimal vimrc?

It works on my side with this vimrc

```vim
set nocompatible
syntax on
filetype plugin indent on
set encoding=utf-8 fileencodings=ucs-bom,utf-8,gbk,gb18030,latin1 termencoding=utf-8

call plug#begin(expand('<sfile>:h') . '/plugged-deoplete/')
Plug 'Shougo/deoplete.nvim'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'roxma/nvim-yarp'
call plug#end()
```

After starting neovim, type `:call deoplete#enable()`

Then the keyword completion is working.

**Comment by Shougo** [comment]
Please test yarp branch.
The keyword completion should not work.
Because I have disabled the initialization.

**Comment by roxma** [comment]
```
[roxma@roxma-pc deoplete.nvim]$ gs
On branch yarp
nothing to commit, working tree clean
[roxma@roxma-pc deoplete.nvim]$ git log
commit b10d6b30c6e7cdc665c420f453b7cc0118c55f32 (grafted, HEAD -> yarp, shougo/yarp, origin/yarp)
Author: Shougo Matsushita <Shougo.Matsu@gmail.com>
Date:   Sun Oct 15 12:14:07 2017 +0900

    Test

```

I'm sure I'm on yarp branch.

I have called `:call deoplete#enable()` manually

**Comment by roxma** [comment]
Sorry, 

Just noticed that I'm on the wrong working directory. I'll test it again.

**Comment by roxma** [comment]
Use this command for starting neovim, `NVIM_PYTHON_LOG_FILE=nvim.log NVIM_PYTHON_LOG_LEVEL=DEBUG vim`, it will generate log files for deoplete module, it's very helpful.

**Comment by Shougo** [comment]
I have merged your PR.
But the freeze does not fixed.

**Comment by Shougo** [comment]
@roxma It does not work in Vim8.  Can you test it?

**Comment by roxma** [comment]
This commit https://github.com/roxma/deoplete.nvim/commit/10b3b58993a8e8ba2601f2060f1c4895063cc400 based on #554 woks on vim8

I cannot send a PR, since it requires manual merge with your latest commit.

**Comment by Shougo** [comment]
I have fixed the commit manually.
But it does not work for me.

**Comment by Shougo** [comment]
neovim_rpc#serveraddr() seems works.

**Comment by roxma** [comment]
Could you test the exact commit of this fork https://github.com/roxma/deoplete.nvim/commit/10b3b58993a8e8ba2601f2060f1c4895063cc400

I pulled your latest commit, but it does not work. It seems other part is not working.

**Comment by Shougo** [comment]
@roxma 
I have get the following errors.

```
Error detected while processing function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[9]..deoplete#init#_channel[9]..<SNR>26_notify[1]..1[4]..yarp#pyx#init[11]..yarp#_serveraddr[9]..neovim_rpc#serveraddr:
line    5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'neovim_rpc_server'
line    6:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'neovim_rpc_server' is not defined
E858: Eval did not return a valid python object
line   11:
E475: Invalid argument:
line   17:
E906: not an open channel
```

**Comment by roxma** [comment]
vim-hug-neovim-rpc is not working

Update both yarp and vim-hug-neovim-rpc to the latest version

Then check the result of these commands

```
set pyxversion
python3 import neovim
python3 import neovim_rpc_server

python import neovim
python import neovim_rpc_server

echo neovim_rpc#serveraddr() 

```

**Comment by Shougo** [comment]
I have updated both.
But it does not work.

**Comment by roxma** [comment]
What's the results of those commands?

**Comment by Shougo** [comment]
`python3 import neovim` does not work.

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/neovim/__init__.py", line 11, in <module>
    from .msgpack_rpc import (ErrorResponse, child_session, socket_session,
  File "/usr/lib/python3.6/site-packages/neovim/msgpack_rpc/__init__.py", line 10, in <module>
    from .session import ErrorResponse, Session
  File "/usr/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 7, in <module>
    import greenlet
ImportError: /usr/lib/python3.6/site-packages/greenlet.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyExc_ValueError
```

**Comment by roxma** [comment]
If `set pyxversion` gets a 3, either make vim8 works with `python3 import neovim` or `set pyxversion=2`

**Comment by Shougo** [comment]
`set pyxversion` is 3, but it does not work...

**Comment by Shougo** [comment]
`import neovim` works in python3 command.
But it does not work in Vim8.

**Comment by roxma** [comment]
`ImportError: /usr/lib/python3.6/site-packages/greenlet.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyExc_ValueError`

I have came across similar issue before. I uninstall `pip uninstall greenlet`, then reinstall it using my system package manager, with `pacman -S python-greenlet` on manjaro

**Comment by Shougo** [comment]
OK.  The errors are fixed.

But the auto completion does not work yet.

**Comment by roxma** [comment]
Is there any error in the log files, with   `export NVIM_PYTHON_LOG_FILE=nvim.log NVIM_PYTHON_LOG_LEVEL=DEBUG `?

**Comment by Shougo** [comment]
@roxma Please test the latest version of deoplete in Vim8.

**Comment by roxma** [comment]
```
2017-10-15 16:46:09,416 [DEBUG @ async_session.py:_on_notification:102] 23204 - received notification: b'deoplete_init', []
2017-10-15 16:46:09,416 [DEBUG @ session.py:_on_notification:216] 23204 - received rpc notification, greenlet <greenlet.greenlet object at 0x7fae96501af8> will handle it
2017-10-15 16:46:09,416 [DEBUG @ msgpack_stream.py:send:33] 23204 - sent [0, 4, 'nvim_call_function', ('deoplete#init#_context', ['Init', []])]
2017-10-15 16:46:09,416 [DEBUG @ base.py:send:113] 23204 - Sending 'b'\x94\x00\x04\xb2nvim_call_function\x92\xb6deoplete#init#_context\x92\xa4Init\x90''
2017-10-15 16:46:09,417 [DEBUG @ session.py:_yielding_request:153] 23204 - yielding from greenlet <greenlet.greenlet object at 0x7fae96501af8> to wait for response
2017-10-15 16:46:09,417 [DEBUG @ msgpack_stream.py:_on_data:54] 23204 - waiting for message...
2017-10-15 16:46:09,417 [DEBUG @ msgpack_stream.py:_on_data:59] 23204 - unpacker needs more data...
2017-10-15 16:46:09,419 [DEBUG @ msgpack_stream.py:_on_data:54] 23204 - waiting for message...
2017-10-15 16:46:09,419 [DEBUG @ msgpack_stream.py:_on_data:56] 23204 - received message: [1, 4, [1, b'Expecting value: line 1 column 1 (char 0)'], None]
2017-10-15 16:46:09,420 [DEBUG @ async_session.py:_on_response:95] 23204 - received response: [1, b'Expecting value: line 1 column 1 (char 0)'], None
2017-10-15 16:46:09,420 [DEBUG @ session.py:response_cb:149] 23204 - response is available for greenlet <greenlet.greenlet object at 0x7fae96501af8>, switching back
2017-10-15 16:46:09,420 [INFO @ session.py:request:97] 23204 - 'Received error: [1, b'Expecting value: line 1 column 1 (char 0)']
2017-10-15 16:46:09,420 [WARNING @ session.py:handler:211] 23204 - error caught while processing notification 'b'deoplete_init' []': Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 207, in handler
    self._notification_cb(name, args)
  File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 171, in filter_notification_cb
    notification_cb(name, args)
  File "/home/roxma/dotfiles/vim/.config/nvim/plugged-deoplete/nvim-yarp/pythonx/yarp.py", line 45, in on_notification
    getattr(module_obj, method)(*args)
  File "/home/roxma/dotfiles/vim/.config/nvim/plugged-deoplete/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 49, in deoplete_init
    deoplete_handler.init_channel()
  File "/home/roxma/dotfiles/vim/.config/nvim/plugged-deoplete/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 25, in init_channel
    self._deoplete = Deoplete(self._vim)
  File "/home/roxma/dotfiles/vim/.config/nvim/plugged-deoplete/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 43, in __init__
    context = self._vim.call('deoplete#init#_context', 'Init', [])
  File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 230, in call
    return self.request('nvim_call_function', name, args, **kwargs)
  File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Expecting value: line 1 column 1 (char 0)'
```

It seems 

```
2017-10-15 16:46:09,416 [DEBUG @ msgpack_stream.py:send:33] 23204 - sent [0, 4, 'nvim_call_function', ('deoplete#init#_context', ['Init', []])]
```

This function failed

**Comment by Shougo** [comment]
I don't understand why it failed.
If I call the function manually in Vim8, it works.

**Comment by Shougo** [comment]
It is vim-hug-neovim-rpc compatibility problem?

**Comment by roxma** [comment]
It seems it is, it gets json decode error:

```
2017-10-15 16:48:48,960 [INFO @ neovim_rpc_server.py:process_pending_requests:338] 23418 - get msg from channel [1]: [0, 4, 'nvim_call_function', ['deoplete#init#_context', ['Init', []]]]
2017-10-15 16:48:48,962 [ERROR @ neovim_rpc_server.py:process_pending_requests:360] 23418 - process failed: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/roxma/dotfiles/vim/.config/nvim/plugged-deoplete/vim-hug-neovim-rpc/pythonx/neovim_rpc_server.py", line 358, in process_pending_requests
    result = _process_request(channel,method,args)
  File "/home/roxma/dotfiles/vim/.config/nvim/plugged-deoplete/vim-hug-neovim-rpc/pythonx/neovim_rpc_server.py", line 396, in _process_request
    return getattr(neovim_rpc_methods,method)(*args)
  File "/home/roxma/dotfiles/vim/.config/nvim/plugged-deoplete/vim-hug-neovim-rpc/pythonx/neovim_rpc_methods.py", line 11, in nvim_call_function
    return json.loads(vim.eval('json_encode(call("%s",g:_neovim_rpc_tmp_args))' % method))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Shougo** [comment]
Hm.  OK.  I wait until it is fixed.

**Comment by roxma** [comment]
Could you remove the func ref in the object returned by the function?

It's hard to make it compatible among vim8, vim8 python binding and neovim-client

**Comment by Shougo** [comment]
What is the funcref?

**Comment by roxma** [comment]
g:deoplete#_yarp contains several funcref.

**Comment by roxma** [comment]
`:echo deoplete#init#_context('Init', [])`

**Comment by Shougo** [comment]
OK.  I have removed it.

It does not work in Vim8 though...

**Comment by roxma** [comment]
Your latest commit works on my side.

Could you post the log files?

**Comment by Shougo** [comment]
```
2017-10-15 18:10:19,299 [DEBUG @ base.py:run:138] 4415 - Entering event loop
2017-10-15 18:10:19,314 [DEBUG @ msgpack_stream.py:_on_data:54] 4415 - waiting for message...
2017-10-15 18:10:19,314 [DEBUG @ msgpack_stream.py:_on_data:56] 4415 - received message: [1, 2, None, b'/home/shougo/work/nvim-yarp/pythonx\n/home/shougo/work/vim-hug-neovim-rpc/pythonx\n/home/shougo/work/deoplete.nvim/rplugin/python3']
2017-10-15 18:10:19,314 [DEBUG @ async_session.py:_on_response:95] 4415 - received response: None, b'/home/shougo/work/nvim-yarp/pythonx\n/home/shougo/work/vim-hug-neovim-rpc/pythonx\n/home/shougo/work/deoplete.nvim/rplugin/python3'
2017-10-15 18:10:19,314 [DEBUG @ base.py:stop:149] 4415 - Stopped event loop
2017-10-15 18:10:19,315 [DEBUG @ msgpack_stream.py:_on_data:54] 4415 - waiting for message...
2017-10-15 18:10:19,315 [DEBUG @ msgpack_stream.py:_on_data:59] 4415 - unpacker needs more data...
2017-10-15 18:10:19,315 [DEBUG @ base.py:run:140] 4415 - Exited event loop
2017-10-15 18:10:19,315 [DEBUG @ msgpack_stream.py:send:33] 4415 - sent [0, 3, 'nvim_call_function', ('yarp#_channel_started', [2, 1])]
2017-10-15 18:10:19,315 [DEBUG @ base.py:send:113] 4415 - Sending 'b'\x94\x00\x03\xb2nvim_call_function\x92\xb5yarp#_channel_started\x92\x02\x01''
2017-10-15 18:10:19,315 [DEBUG @ base.py:run:138] 4415 - Entering event loop
2017-10-15 18:10:19,336 [DEBUG @ msgpack_stream.py:_on_data:54] 4415 - waiting for message...
2017-10-15 18:10:19,336 [DEBUG @ msgpack_stream.py:_on_data:56] 4415 - received message: [1, 3, None, 0]
2017-10-15 18:10:19,336 [DEBUG @ async_session.py:_on_response:95] 4415 - received response: None, 0
2017-10-15 18:10:19,336 [DEBUG @ base.py:stop:149] 4415 - Stopped event loop
2017-10-15 18:10:19,336 [DEBUG @ msgpack_stream.py:_on_data:54] 4415 - waiting for message...
2017-10-15 18:10:19,337 [DEBUG @ msgpack_stream.py:_on_data:59] 4415 - unpacker needs more data...
2017-10-15 18:10:19,337 [DEBUG @ base.py:run:140] 4415 - Exited event loop
2017-10-15 18:10:19,347 [DEBUG @ base.py:run:138] 4415 - Entering event loop
2017-10-15 18:10:19,377 [DEBUG @ msgpack_stream.py:_on_data:54] 4415 - waiting for message...
2017-10-15 18:10:19,377 [DEBUG @ msgpack_stream.py:_on_data:56] 4415 - received message: [2, b'deoplete_init', []]
2017-10-15 18:10:19,378 [DEBUG @ async_session.py:_on_notification:102] 4415 - received notification: b'deoplete_init', []
2017-10-15 18:10:19,378 [DEBUG @ session.py:_on_notification:216] 4415 - received rpc notification, greenlet <greenlet.greenlet object at 0x7f622de65800> will handle it
2017-10-15 18:10:19,378 [DEBUG @ msgpack_stream.py:send:33] 4415 - sent [0, 4, 'nvim_call_function', ('deoplete#init#_context', ['Init', []])]
2017-10-15 18:10:19,378 [DEBUG @ base.py:send:113] 4415 - Sending 'b'\x94\x00\x04\xb2nvim_call_function\x92\xb6deoplete#init#_context\x92\xa4Init\x90''
2017-10-15 18:10:19,378 [DEBUG @ session.py:_yielding_request:153] 4415 - yielding from greenlet <greenlet.greenlet object at 0x7f622de65800> to wait for response
2017-10-15 18:10:19,378 [DEBUG @ msgpack_stream.py:_on_data:54] 4415 - waiting for message...
2017-10-15 18:10:19,378 [DEBUG @ msgpack_stream.py:_on_data:59] 4415 - unpacker needs more data...
2017-10-15 18:10:25,138 [DEBUG @ base.py:_on_signal:153] 4415 - Received SIGTERM
2017-10-15 18:10:25,138 [DEBUG @ base.py:stop:149] 4415 - Stopped event loop
2017-10-15 18:10:25,138 [DEBUG @ base.py:run:140] 4415 - Exited event loop
```

It seems crashed.

**Comment by roxma** [comment]
I don't think so, Vim sends SIGTERM when it exits, which is 6 seconds after initialized.

There's another useful log file for the neovim_rpc_server module

**Comment by Shougo** [comment]
I don't find the any errors.

```
2017-10-15 18:10:19,292 [INFO @ neovim_rpc_server.py:process_pending_requests:369] 4411 - sended
2017-10-15 18:10:19,299 [INFO @ neovim_rpc_server.py:handle:171] 4411 - unpacked: [0, 2, b'nvim_eval', [b'globpath(&rtp,"pythonx",1) . "\\n" . globpath(&rtp,"rplugin/python3",1)']]
2017-10-15 18:10:19,299 [INFO @ neovim_rpc_server.py:notify:71] 4411 - sending notification: ["ex", "call neovim_rpc#_callback()"]
2017-10-15 18:10:19,313 [INFO @ neovim_rpc_server.py:process_pending_requests:326] 4411 - process_pending_requests
2017-10-15 18:10:19,313 [INFO @ neovim_rpc_server.py:process_pending_requests:338] 4411 - get msg from channel [1]: [0, 2, 'nvim_eval', ['globpath(&rtp,"pythonx",1) . "\\n" . globpath(&rtp,"rplugin/python3",1)']]
2017-10-15 18:10:19,313 [INFO @ neovim_rpc_server.py:process_pending_requests:366] 4411 - sending result: [1, 2, None, '/home/shougo/work/nvim-yarp/pythonx\n/home/shougo/work/vim-hug-neovim-rpc/pythonx\n/home/shougo/work/deoplete.nvim/rplugin/python3']
2017-10-15 18:10:19,314 [INFO @ neovim_rpc_server.py:process_pending_requests:369] 4411 - sended
2017-10-15 18:10:19,315 [INFO @ neovim_rpc_server.py:handle:171] 4411 - unpacked: [0, 3, b'nvim_call_function', [b'yarp#_channel_started', [2, 1]]]
2017-10-15 18:10:19,315 [INFO @ neovim_rpc_server.py:notify:71] 4411 - sending notification: ["ex", "call neovim_rpc#_callback()"]
2017-10-15 18:10:19,335 [INFO @ neovim_rpc_server.py:process_pending_requests:326] 4411 - process_pending_requests
2017-10-15 18:10:19,335 [INFO @ neovim_rpc_server.py:process_pending_requests:338] 4411 - get msg from channel [1]: [0, 3, 'nvim_call_function', ['yarp#_channel_started', [2, 1]]]
2017-10-15 18:10:19,335 [INFO @ neovim_rpc_server.py:process_pending_requests:366] 4411 - sending result: [1, 3, None, 0]
2017-10-15 18:10:19,335 [INFO @ neovim_rpc_server.py:process_pending_requests:369] 4411 - sended
2017-10-15 18:10:19,336 [INFO @ neovim_rpc_server.py:notify:227] 4411 - notify channel[1]: [2, 'deoplete_init', []]
2017-10-15 18:10:19,378 [INFO @ neovim_rpc_server.py:handle:171] 4411 - unpacked: [0, 4, b'nvim_call_function', [b'deoplete#init#_context', [b'Init', []]]]
2017-10-15 18:10:19,379 [INFO @ neovim_rpc_server.py:notify:71] 4411 - sending notification: ["ex", "call neovim_rpc#_callback()"]
2017-10-15 18:10:19,494 [INFO @ neovim_rpc_server.py:process_pending_requests:326] 4417 - process_pending_requests
```

**Comment by Shougo** [comment]
I don't find any errors, but it does not work.
Why?
It takes many times?

**Comment by roxma** [comment]
```
2017-10-15 18:10:19,378 [INFO @ neovim_rpc_server.py:handle:171] 4411 - unpacked: [0, 4, b'nvim_call_function', [b'deoplete#init#_context', [b'Init', []]]]
2017-10-15 18:10:19,379 [INFO @ neovim_rpc_server.py:notify:71] 4411 - sending notification: ["ex", "call neovim_rpc#_callback()"]
2017-10-15 18:10:19,494 [INFO @ neovim_rpc_server.py:process_pending_requests:326] 4417 - process_pending_requests
```

neovim_rpc_server received `deoplete#init#_context' function call, but it fails to pop it from the queue. At line  332 of vim-hug-neovim-rpc/pythonx/neovim_rpc_server.py, https://github.com/roxma/vim-hug-neovim-rpc/blob/d0c5e1f0e2f3ae5d412cae692c9c1d57aadaa9d2/pythonx/neovim_rpc_server.py#L332

So it freezes on your side.

I can't figure out why, though.

**Comment by Shougo** [comment]
Hm....

But it works in your environment doesn't it?
I don't understand why.

Using vim-hug-neovim seems hard to debug.

**Comment by Shougo** [comment]
My Vim version is 8.0.1194.
Please test the latest version.

**Comment by roxma** [comment]
It is hard to debug.

I mostly rely on logging.

Mine is 8.0.1159 , I'll find and test  8.0.1194.

By the way, line 332 may not be the issue, it uses non-blocking queue. You could try edit the python script, and add some log around 332 to see what we get.

**Comment by Shougo** [comment]
> Mine is 8.0.1159 , I'll find and test 8.0.1194.

It seems old.
Vim has changed channel/terminal feature for after that.

**Comment by roxma** [comment]
Unfortunately,  8.0.1194 also works

deoplete

I cannot reproduce the error.

**Comment by Shougo** [comment]
My minimal vimrc is:

```vim
set runtimepath+=~/work/deoplete.nvim/
set runtimepath+=~/work/nvim-yarp/
set runtimepath+=~/work/vim-hug-neovim-rpc/

filetype plugin indent on
syntax enable

let g:deoplete#enable_at_startup = 1
```

Why it does not work?

**Comment by Shougo** [comment]
`:call deoplete#enable()` seems freezed.

**Comment by roxma** [comment]
You might need to debug it on your own, add more logging script for debug information.

Or maybe post a  docker image, so that I can debug on it.

**Comment by Shougo** [comment]
I don't want to debug vim-hug-neovim-rpc plugin...
I have not much time for it.

**Comment by Shougo** [comment]
My environment is Manjaro.
I will test it in Ubuntu 16.04 later though.

**Comment by roxma** [comment]
I encountered an error with your minimal vimrc

```
[roxma@roxma-pc nvim]$ cat depolete_init.vim 
set runtimepath+=/home/roxma/.config/nvim/plugged-deoplete/deoplete.nvim
set runtimepath+=/home/roxma/.config/nvim/plugged-deoplete/nvim-yarp
set runtimepath+=/home/roxma/.config/nvim/plugged-deoplete/vim-hug-neovim-rpc

filetype plugin indent on
syntax enable

let g:deoplete#enable_at_startup = 1
[roxma@roxma-pc nvim]$ vim8 -u ./depolete_init.vim  
Error detected while processing function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[9]..deoplete#init#_channel:
line    3:
E10: \ should be followed by /, ? or &
Press ENTER or type command to continue
```

**Comment by roxma** [comment]
`set nocompatible` is required.

**Comment by Shougo** [comment]
OK.  I get it.

`call deoplete#enable()` manually works.
But `let g:deoplete#enable_at_startup = 1` does not work.

**Comment by Shougo** [comment]
I don't know why.

**Comment by roxma** [comment]
FYI, My system is also manjaro

```
set runtimepath+=/home/roxma/.config/nvim/plugged-deoplete/deoplete.nvim
set runtimepath+=/home/roxma/.config/nvim/plugged-deoplete/nvim-yarp
set runtimepath+=/home/roxma/.config/nvim/plugged-deoplete/vim-hug-neovim-rpc

filetype plugin indent on
syntax enable
set nocompatible


let g:deoplete#enable_at_startup = 1
```

`let g:deoplete#enable_at_startup = 1` also works.

**Comment by Shougo** [comment]
It seems plugins load timing problem.

I have fixed it.

**Comment by roxma** [comment]
Good!

 But we still can't figure out why it's happening.

**Comment by Shougo** [comment]
It works on minimal environment.
But it does not work on my vimrc.
I will test it later.

**Comment by Shougo** [comment]
I get the problem.
Fixed.

**Comment by Shougo** [comment]
@roxma Thanks for your effort.

**Comment by Shougo** [comment]
I will merge the branch on the weekend.
Please test it until the merge.

**Comment by AlexMasterov** [comment]
Vim8 (1203)
Python 3.6.3 (2c5fed8) / neovim (0.1.13)
Windows 10 (16299.15)
The same minimal vimrc.

`let g:deoplete#enable_at_startup = 1` ->
`call deoplete#enable()` ->
`call g:deoplete#_yarp.notify('deoplete_init')` is freezed.

**Comment by Shougo** [comment]
@AlexMasterov Please check the issue.
https://github.com/roxma/vim-hug-neovim-rpc/issues/9

**Comment by AlexMasterov** [comment]
@Shougo 
I checked the Python $PATH using `echo exepath('python3')`, and he pointed to the third-party (msys2) python3 executable. This was fixed by specifying `g:python3_host_prog`. Now it seems to work for me.

**Comment by Shougo** [comment]
Thank you for your testing.
It seems vim-hug-neovim-rpc problem...

**Comment by Shougo** [comment]
I will add the problem in FAQ.

**Comment by tracyone** [comment]
macOS 10.13

vim version:8.0 1194

Work but it is a bit slow at startup.

Another problem is neovim. See following screenshot.

```vim
    Plug 'Shougo/deoplete.nvim'
    Plug 'zchee/deoplete-clang'
    if !te#env#IsNvim()
        Plug 'roxma/nvim-yarp'
        Plug 'roxma/vim-hug-neovim-rpc'
    endif
```

**Comment by roxma** [comment]
@tracyone 

    Plug 'Shougo/deoplete.nvim'
    Plug 'zchee/deoplete-clang'
    Plug 'roxma/nvim-yarp'
    if !te#env#IsNvim()
        Plug 'roxma/vim-hug-neovim-rpc'
    endif

Move yarp out of the if block

**Comment by Shougo** [comment]
@tracyone Please read the error messages...

**Comment by Shougo** [comment]
I have added Python3 detection.

**Comment by xtal8** [comment]
@roxma 
Is it necessary to have `Plug 'roxma/vim-hug-neovim-rpc'` inside if block?  Isn't it loaded only on demand because it only contains autoload folder?

**Comment by Shougo** [comment]
@xtal8 vim-hug-neovim-rpc is needed for Vim.
nvim-yarp is needed for both Vim and neovim.

**Comment by wsdjeg** [comment]
@Shougo IN old version, deoplete do not need vim-yarp by default in Neovim. I think we should keep this behavior！

many people use Neovim only. and some old user of deoplete do not install vim-yarp.

**Comment by Shougo** [comment]
> @Shougo IN old version, deoplete do not need vim-yarp by default in Neovim. I think we should keep this behavior！

> many people use Neovim only. and some old user of deoplete do not install vim-yarp.

Of course, I have thought the problem.

**Comment by Shougo** [comment]
But we have many `:UpdateRemotePlugins` issues.

https://github.com/Shougo/deoplete.nvim/issues?q=is%3Aissue+updateremoteplugins+is%3Aclosed

This is annoying.

**Comment by wsdjeg** [comment]
@Shougo  this kind issues should be fixed by neovim itself instead of plugin. I am not sure if there is any PR about it.

**Comment by Shougo** [comment]
And I don't want to keep neovim code and Vim8 code.

> @Shougo this kind issues should be fixed by neovim itself instead of plugin. I am not sure if there is any PR about it.

Yes, and it is not fixed yet!

**Comment by wsdjeg** [comment]
hmm. ok I got it.

**Comment by Shougo** [comment]
OK.  I will consider the problem.

**Comment by Shougo** [comment]
The merge needs more time.
Please wait.

**Comment by Shougo** [comment]
I have fixed the compatibility problems.

@wsdjeg Please test it.

**Comment by Shougo** [comment]
Merged.

**Comment by wsdjeg** [comment]
nice work！

**Comment by mreishus** [comment]
Great job.  It's working for me in windows with vim 8.

Here are my notes on getting the python support in vim to work on windows if anyone googling finds this:
```
" 0. Install chocolately package manager.
" 1. If you installed vim on your own, uninstall it and run "choco install vim".
" 1.5.  The choco version of vim is installed with dynamic python support, so you only need to have a python35.dll in your path.  Note that later versions of the choco vim package may bump this to 3.6, and later steps will need to be modified.
" 2. choco install python3 --version 3.5.4
" 3. choco pin add -n=python3 --version 3.5.4
" 4. Add C:\python35 to path and run refreshenv in powershell
" 5. Copy C:\Python35\python.exe to C:\Python35\python3.exe 
" 6. C:\Python35\Scripts\pip.exe install neovim
```

**Pull request merged**
